name: Release

on:
  push:
    tags:
      - "v*"

jobs:

  publish-library:
    name: Publish Python Package (library)
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/irsol-data-pipeline
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v5

      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Build distribution
        run: uv build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1


  publish-cli:
    name: Publish Python Package (CLI)
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/irsol-data-pipeline-cli
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - name: Set up uv
        uses: astral-sh/setup-uv@v7

      - name: Transform to CLI Package
        run: |
          # 1. Export the full transitive tree from uv.lock
          uv export --format requirements.txt --no-dev --no-hashes > locked_deps.txt

          # 2. Patch pyproject.toml using a Python one-liner
          # Note: we use 'tomli-w' via uvx to keep the runner clean
          # Note2: we use 'tomli' as tomllib i s not available on python3.10
          uvx --with tomli --with tomli-w python -c "
          import tomli, tomli_w
          with open('pyproject.toml', 'rb') as f:
              data = tomli.load(f)
          with open('locked_deps.txt', 'r') as f:
              locked = [l.strip() for l in f if l.strip()]
              locked = [l for l in locked if not l.startswith('#')]
              locked = [l for l in locked if not l.startswith('-e')]

          # Append -cli to name and replace dependencies with the lockfile export
          data['project']['name'] = f'{data[\"project\"][\"name\"]}-cli'
          data['project']['dependencies'] = locked

          with open('pyproject.toml', 'wb') as f:
              tomli_w.dump(data, f)
          "

      - name: Build distribution
        run: uv build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
